# -*- coding: utf-8 -*-
"""HybridImages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hshVEbYlGLsAbuh0iZa05mWqjmjgh1hv
"""

from skimage.io import imread
import matplotlib.pyplot as plt
import scipy.fftpack as fp
import scipy.fftpack
import numpy as np
import cv2
import os

im2 = np.mean(imread('v.jpg'), axis=2) # assuming an RGB image
plt.figure(figsize=(10,10))
plt.imshow(im2, cmap=plt.cm.gray)
plt.axis('off')
plt.show()

im = np.mean(imread('s.jpg'), axis=2) # assuming an RGB image
im = im[:455, :]
im = cv2.resize(im, dsize=(im2.shape[1], im2.shape[0]), interpolation=cv2.INTER_CUBIC)
plt.figure(figsize=(10,10))
plt.imshow(im, cmap=plt.cm.gray)
plt.axis('off')
plt.show()

# plt.figure(figsize=(10,10))
# plt.imshow(im+im2, cmap=plt.cm.gray)
# plt.axis('off')
# plt.show()


print(im.shape, im2.shape)

F1 = fp.fft2((im).astype(float))
F2 = fp.fftshift(F1)
plt.figure(figsize=(10,10))
plt.imshow( (20*np.log10( 0.1 + F2)).astype(int), cmap=plt.cm.gray)
plt.show()


F12 = fp.fft2((im2).astype(float))
F22 = fp.fftshift(F12)
plt.figure(figsize=(10,10))
plt.imshow( (20*np.log10( 0.1 + F22)).astype(int), cmap=plt.cm.gray)
plt.show()

(w, h) = im.shape
half_w, half_h = int(w/2), int(h/2)

F2_bkp = F2
F22_bkp = F22
os.system("mkdir -p OutputImages")

for n in range(8,18):
  for n2 in range(25, 45):
    # high pass filter
    #n = 8
    for i in range(0, w):
      for j in range(0, h):
        xDist = i - half_w;
        yDist = j - half_h;
        if(((xDist*xDist) + (yDist*yDist)) < n*n):
          F2[i][j] = 0
    # plt.figure(figsize=(10,10))
    # plt.imshow( (20*np.log10( 0.1 + F2)).astype(int))
    # plt.show()


    (w2, h2) = im2.shape
    half_w2, half_h2 = int(w2/2), int(h2/2)

    # high pass filter
    #n2 = 35
    for i in range(0, w2):
      for j in range(0, h2):
        xDist = i - half_w2;
        yDist = j - half_h2;
        if(((xDist*xDist) + (yDist*yDist)) > n2*n2):
          F22[i][j] = 0
    # plt.figure(figsize=(10,10))
    # plt.imshow( (20*np.log10( 0.1 + F22)).astype(int))
    # plt.show()

    im1 = fp.ifft2(fp.ifftshift(F2)).real
    # plt.figure(figsize=(10,10))
    # plt.imshow(im1, cmap='gray')
    # plt.axis('off')
    # plt.show()

    im12 = fp.ifft2(fp.ifftshift(F22)).real
    # plt.figure(figsize=(10,10))
    # plt.imshow(im12, cmap='gray')
    # plt.axis('off')
    # plt.show()


    im3 = im1 + im12
    # plt.figure(figsize=(10,10))
    # plt.imshow(im3, cmap='gray')
    # plt.axis('off')
    # plt.show()
    cv2.imwrite("OutputImages/outputn1_%d_n2_%d.jpg" % (n,n2),im3)
    print("OutputImages/outputn1_%d_n2_%d.jpg" % (n,n2))



